#!/usr/bin/env python3



from __future__ import annotations

import argparse
from pathlib import Path

from generate_botw_item_text import cpp_string, decode_msbt_text, sarc_data


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("bootup_language_pack", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    bootup = sarc_data(args.bootup_language_pack.read_bytes())
    message_file = bootup.get_file("Message/Msg_USen.product.ssarc")
    if message_file is None:
        raise RuntimeError("Bootup language pack does not contain Msg_USen.product.ssarc")
    messages = sarc_data(bytes(message_file.data))

    rows: dict[str, str] = {}
    for entry in messages.get_files():
        if not entry.name.startswith("QuestMsg/QL_") or not entry.name.endswith(".msbt"):
            continue
        for label, value in decode_msbt_text(bytes(entry.data)).items():
            clean = value.strip()
            if clean:
                rows[label] = clean

    ordered = sorted(rows.items())
    lines = [
        "// Generated by tools/dualscreen/generate_botw_quest_text.py. Do not edit.",
        f"constexpr std::array<QuestText, {len(ordered)}> BotwQuestText{{{{",
    ]
    lines.extend(
        f"    QuestText{{{cpp_string(label)}, {cpp_string(text)}}},"
        for label, text in ordered
    )
    lines.append("}};")
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated {len(ordered)} localized quest messages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
