param(
    [Parameter(Mandatory = $true)]
    [string]$StaticMapJson,
    [Parameter(Mandatory = $true)]
    [string]$DungeonTextJson,
    [Parameter(Mandatory = $true)]
    [string]$AndroidAsset,
    [Parameter(Mandatory = $true)]
    [string]$NativeInclude
)

$ErrorActionPreference = 'Stop'

function Get-Crc32([string]$Value) {
    [uint64]$crc = 0xFFFFFFFFL
    foreach ($byte in [System.Text.Encoding]::UTF8.GetBytes($Value)) {
        $crc = ($crc -bxor [uint64]$byte) -band 0xFFFFFFFFL
        for ($bit = 0; $bit -lt 8; $bit++) {
            if (($crc -band 1) -ne 0) {
                $crc = (($crc -shr 1) -bxor 0xEDB88320L) -band 0xFFFFFFFFL
            } else {
                $crc = ($crc -shr 1) -band 0xFFFFFFFFL
            }
        }
    }
    return [uint32](($crc -bxor 0xFFFFFFFFL) -band 0xFFFFFFFFL)
}

function Escape-Cpp([string]$Value) {
    return $Value.Replace('\', '\\').Replace('"', '\"')
}

$staticMap = Get-Content -Raw -LiteralPath $StaticMapJson | ConvertFrom-Json
$dungeonText = Get-Content -Raw -LiteralPath $DungeonTextJson | ConvertFrom-Json
$dungeons = @($staticMap.markers.Dungeon)
if ($dungeons.Count -ne 136) {
    throw "Expected all 136 BOTW shrines, found $($dungeons.Count)."
}

$assetRows = [System.Collections.Generic.List[object]]::new()
$cppRows = [System.Collections.Generic.List[string]]::new()
for ($index = 0; $index -lt $dungeons.Count; $index++) {
    $dungeon = $dungeons[$index]
    $id = [string]$dungeon.MessageID
    $name = [string]$dungeonText.PSObject.Properties[$id].Value
    $trial = [string]$dungeonText.PSObject.Properties["${id}_sub"].Value
    if ([string]::IsNullOrWhiteSpace($name)) {
        throw "Missing localized shrine name for $id."
    }

    $assetRows.Add([ordered]@{
        index = $index
        id = $id
        name = $name
        trial = $trial
        x = [double]$dungeon.Translate.X
        y = [double]$dungeon.Translate.Y
        z = [double]$dungeon.Translate.Z
    })

    $enteredHash = Get-Crc32 "Enter_$id"
    $clearedHash = Get-Crc32 "Clear_$id"
    $mapName = Escape-Cpp ([string]$dungeon.WarpDestMapName)
    $positionName = Escape-Cpp ([string]$dungeon.WarpDestPosName)
    $cppRows.Add(
        ('    ShrineDefinition{{"{0}", "{1}", "{2}", 0x{3:X8}U, 0x{4:X8}U}},' -f `
            (Escape-Cpp $id), $mapName, $positionName, $enteredHash, $clearedHash)
    )
}

$assetDirectory = Split-Path -Parent $AndroidAsset
$nativeDirectory = Split-Path -Parent $NativeInclude
[System.IO.Directory]::CreateDirectory($assetDirectory) | Out-Null
[System.IO.Directory]::CreateDirectory($nativeDirectory) | Out-Null

$assetJson = ConvertTo-Json -InputObject @($assetRows) -Depth 4 -Compress
[System.IO.File]::WriteAllText($AndroidAsset, $assetJson + [Environment]::NewLine,
    [System.Text.UTF8Encoding]::new($false))

$cpp = @(
    '// Generated by tools/botw-companion/generate_shrines.ps1. Do not edit by hand.'
    'constexpr std::array<ShrineDefinition, 136> BotwShrines{{'
) + $cppRows + @('}};', '')
[System.IO.File]::WriteAllLines($NativeInclude, $cpp, [System.Text.UTF8Encoding]::new($false))

Write-Host "Generated $($assetRows.Count) shrine records."
